### ISSUE TITLE
Crash when loaded to zalith launcher

### ISSUE THREAD

**Issue by CubyMC** [MovTery/ZalithLauncher#205]
### Issue Type / 问题类型

Game Issue / 游戏问题

### Issue Description / 问题描述

When I launch the launcher and I seem find. A minute later it crash.

### Log File / 日志文件

java.lang.NullPointerException: Parameter specified as non-null is null: method com.movtery.zalithlauncher.event.sticky.MinecraftVersionValueEvent.<init>, parameter list
	at com.movtery.zalithlauncher.event.sticky.MinecraftVersionValueEvent.<init>(Unknown Source:2)
	at net.kdt.pojavlaunch.LauncherActivity.lambda$onCreate$10(LauncherActivity.java:327)
	at net.kdt.pojavlaunch.LauncherActivity$$ExternalSyntheticLambda18.onVersionDone(D8$$SyntheticClass:0)
	at net.kdt.pojavlaunch.tasks.AsyncVersionList.lambda$getVersionList$0$net-kdt-pojavlaunch-tasks-AsyncVersionList(AsyncVersionList.java:56)
	at net.kdt.pojavlaunch.tasks.AsyncVersionList$$ExternalSyntheticLambda0.run(D8$$SyntheticClass:0)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.lang.Thread.run(Thread.java:923)

### Reproduction Steps / 复现步骤

```markdown
1. Open Zalith Launcher
2. A minute later
3. CRASH

It work the first time. The second that happen.
Already try uninstalling and reinstalling
```

### Android Version / Android 版本

10

### App Version / 应用版本

1.3.6.1

### Selected Renderer / 选择的渲染器

Holy GL4ES

### Device Information / 设备信息

Redmi note 8 Android 10 arm64

### This issue has not been reported before / 这个问题还没有人反馈过

- [X] I have checked the Issues and found no similar issue reported / 我已经查看过 Issues，并且没有发现与之类似的问题被反馈

**Comment by MovTery** [comment]
https://github.com/MovTery/ZalithLauncher/actions/runs/11537556709
