### ISSUE TITLE
Bright screen bug how to fix pls

### ISSUE THREAD

**Issue by Mushrush825** [MovTery/ZalithLauncher#213]
### Issue Type / 问题类型

Game Issue / 游戏问题

### Issue Description / 问题描述

When I launch zenith for the first time the game became really bright I don't know why this was happening all I know is the game became really bright so zenith devs give me a tutorial how to fix this I really want to play java without lag so fix it asap plsss🙏😭

### Log File / 日志文件

[15:29:00] [Client thread/WARN]: Skipping bad option: lastServer:
[15:29:00] [Client thread/INFO]: LWJGL Version: 3.3.3-snapshot
[15:29:00] [Client thread/INFO]: [STDOUT]: LWJGLX: GL caps init
[LWJGL] [ERROR] Incompatible Java and native library versions detected.
Possible reasons:
	a) -Djava.library.path is set to a folder containing shared libraries of an older LWJGL version.
	b) The classpath contains jar files of an older LWJGL version.
Possible solutions:
	a) Make sure to not set -Djava.library.path (it is not needed for developing with LWJGL 3) or make
	   sure the folder it points to contains the shared libraries of the correct LWJGL version.
	b) Check the classpath and make sure to only have jar files of the same LWJGL version in it.
Initialising gl4es
v1.1.5 built on Jul 14 2024 19:34:14
Using GLES 2.0 backend
loaded: libGLESv2.so
loaded: libEGL.so
Using GLES 2.0 backend
Hardware Full NPOT detected and used
Extension GL_EXT_blend_minmax  detected and used
Extension GL_EXT_draw_buffers  detected and used
FBO are in core, and so used
PointSprite are in core, and so used
CubeMap are in core, and so used
BlendColor is in core, and so used
Blend Subtract is in core, and so used
Blend Function and Equation Separation is in core, and so used
Texture Mirrored Repeat is in core, and so used
Extension GL_OES_mapbuffer  detected
Extension GL_OES_element_index_uint  detected and used
Extension GL_OES_packed_depth_stencil  detected and used
Extension GL_OES_depth24  detected and used
Extension GL_OES_rgb8_rgba8  detected and used
Extension GL_EXT_multi_draw_arrays  detected
Extension GL_EXT_texture_format_BGRA8888  detected and used
Extension GL_OES_depth_texture  detected and used
Extension GL_OES_texture_stencil8  detected and used
Extension GL_EXT_texture_rg  detected and used
Extension GL_OES_texture_float  detected and used
Extension GL_OES_texture_half_float  detected and used
Extension GL_EXT_color_buffer_float  detected and used
Extension GL_OES_fragment_precision_high  detected and used
Extension GL_EXT_shader_texture_lod detected and used
Max vertex attrib: 16
Extension GL_OES_standard_derivatives  detected and used
Extension GL_OES_get_program_binary  detected and used
Number of supported Program Binary Format: 1
Max texture size: 4096
Max Varying Vector: 15
Texture Units: 16/16 (hardware: 16), Max lights: 8, Max planes: 6
Extension GL_EXT_texture_filter_anisotropic  detected and used
Max Anisotropic filtering: 2
Hardware vendor is Imagination Technologies
GLSL 300 es supported
GLSL 310 es supported and used
GLSL 320 es supported
Max Color Attachments: 8 / Draw buffers: 8
EGLImage to Texture2D supported
EGLImage to RenderBuffer supported
ignore MipMap
glGetError() always return GL_NOERROR
Targeting OpenGL 2.1
No hack in shader converter to define overloaded function with int
Not trying to batch small subsequent glDrawXXXX
try to use VBO
FBO workaround for using binded texture enabled
Force texture for Attachment color0 on FBO
Hack to trigger a SwapBuffers when a Full Framebuffer Blit on default FBO is done
Force normals to be normalized on FPE shaders
glX Will try to recycle EGL Surface
Current folder is:/storage/emulated/0/games/ZalithLauncher/.minecraft/instance/default
[15:29:01] [Client thread/INFO]: [STDERR]: java.lang.NullPointerException
[15:29:01] [Client thread/INFO]: [STDERR]: 	at org.lwjgl.system.Pointer$Default.<init>(Pointer.java:88)
[15:29:01] [Client thread/INFO]: [STDERR]: 	at org.lwjgl.system.CustomBuffer.<init>(CustomBuffer.java:25)
[15:29:01] [Client thread/INFO]: [STDERR]: 	at org.lwjgl.system.StructBuffer.<init>(StructBuffer.java:20)
[15:29:01] [Client thread/INFO]: [STDERR]: 	at org.lwjgl.glfw.GLFWImage$Buffer.<init>(GLFWImage.java:303)
[15:29:01] [Client thread/INFO]: [STDERR]: 	at org.lwjgl.opengl.Display.setIcon(Display.java:946)
[15:29:01] [Client thread/INFO]: [STDERR]: 	at bib.av(SourceFile:661)
[15:29:01] [Client thread/INFO]: [STDERR]: 	at bib.aq(SourceFile:456)
[15:29:01] [Client thread/INFO]: [STDERR]: 	at bib.a(SourceFile:404)
[15:29:01] [Client thread/INFO]: [STDERR]: 	at net.minecraft.client.main.Main.main(SourceFile:123)
EGLBridge: Binding to OpenGL ES
[15:29:02] [Client thread/INFO]: [STDOUT]: LWJGLX: ready-handle context created
[15:29:02] [Client thread/INFO]: [STDOUT]: Grab: false
[15:29:02] [Client thread/INFO]: Reloading ResourceManager: Default
[15:29:04] [Sound Library Loader/INFO]: Starting up SoundSystem...
[15:29:04] [Thread-2/INFO]: Initializing LWJGL OpenAL
[15:29:04] [Thread-2/INFO]: (The LWJGL binding of OpenAL.  For more information, see http://www.lwjgl.org)
[LWJGL] [ERROR] Incompatible Java and native library versions detected.
Possible reasons:
	a) -Djava.library.path is set to a folder containing shared libraries of an older LWJGL version.
	b) The classpath contains jar files of an older LWJGL version.
Possible solutions:
	a) Make sure to not set -Djava.library.path (it is not needed for developing with LWJGL 3) or make
	   sure the folder it points to contains the shared libraries of the correct LWJGL version.
	b) Check the classpath and make sure to only have jar files of the same LWJGL version in it.

[ALSOFT] (EE) Failed to set real-time priority for thread: Operation not permitted (1)
[15:29:04] [Thread-2/INFO]: OpenAL initialized.
[15:29:04] [Sound Library Loader/INFO]: Sound engine started
[15:29:19] [Client thread/INFO]: Created: 1024x512 textures-atlas
[15:29:27] [Client thread/WARN]: ERROR : Generic error while loading narrator : 

There is an incompatible JNA native library installed on this system
Expected: 6.1.6
Found:    7.0.2
(at /data/app/com.movtery.zalithlauncher-qABcE2MSVxBJR4kfzp6MBg==/lib/arm64/libjnidispatch.so).
To resolve this issue you may do one of the following:
 - remove or uninstall the offending library
 - set the system property jna.nosys=true
 - set jna.boot.library.path to include the path to the version of the 
   jnidispatch library included with the JNA jar file you are using

[15:29:27] [Client thread/WARN]: Failed to load shader: minecraft:shaders/post/entity_outline.json
nj: Invalid shaders/program/entity_sobel.fsh: Couldn't compile fragment program: Compile failed.
ERROR: 0:65: 'texture2D' : undeclared identifier
ERROR: 0:65: invalid function call
2 compilation errors. No code generated.
	at cda.a(SourceFile:70) ~[1.12.2.jar:?]
	at ccx.<init>(SourceFile:134) ~[1.12.2.jar:?]
	at ccz.<init>(SourceFile:28) ~[1.12.2.jar:?]
	at ccy.a(SourceFile:274) ~[1.12.2.jar:?]
	at ccy.a(SourceFile:141) ~[1.12.2.jar:?]
	at ccy.a(SourceFile:89) ~[1.12.2.jar:?]
	at ccy.<init>(SourceFile:56) ~[1.12.2.jar:?]
	at buy.b(SourceFile:246) [1.12.2.jar:?]
	at bib.aq(SourceFile:582) [1.12.2.jar:?]
	at bib.a(SourceFile:404) [1.12.2.jar:?]
	at net.minecraft.client.main.Main.main(SourceFile:123) [1.12.2.jar:?]
[15:29:30] [Realms Notification Availability checker #1/INFO]: Could not authorize you against Realms server: Invalid session id

### Screenshots or Videos / 截图或视频

https://github.com/user-attachments/assets/78151ea2-1606-4e0c-bf30-d31633dfbee7

![Screenshot_2024-11-01-15-24-28-33_b9530d923fff59dfb5cdc6a8e8e3c8af](https://github.com/user-attachments/assets/a47c082f-f776-496f-a284-f791375f53bf)
![Screenshot_2024-11-01-15-24-34-62_b9530d923fff59dfb5cdc6a8e8e3c8af](https://github.com/user-attachments/assets/d808e3d7-ca18-4e3d-a005-b6e3cabbe6b4)
![Screenshot_2024-11-01-15-24-53-08_b9530d923fff59dfb5cdc6a8e8e3c8af](https://github.com/user-attachments/assets/d339b02b-f5d2-492b-9a9c-1d30d54b9b5d)
![Screenshot_2024-11-01-15-24-58-21_b9530d923fff59dfb5cdc6a8e8e3c8af](https://github.com/user-attachments/assets/3dfd3dc4-8354-49dd-92a2-987159e60709)
![Screenshot_2024-11-01-15-25-05-39_b9530d923fff59dfb5cdc6a8e8e3c8af](https://github.com/user-attachments/assets/90f64b7d-6e6b-4a8d-91d6-b0b708c86e65)
![Screenshot_2024-11-01-15-25-16-61_b9530d923fff59dfb5cdc6a8e8e3c8af](https://github.com/user-attachments/assets/c4cb3912-be41-40c6-81a1-d3dbf007405a)

### Reproduction Steps / 复现步骤

```markdown
1.i open the launcher
2.i start the game version 1.12.2
3.the bright screen appears and i don't know why
4.it the same in the settings, multiplayer,and world
```

### Android Version / Android 版本

9

### App Version / 应用版本

1.3.6.2

### Selected Renderer / 选择的渲染器

Holy GL4ES

### Device Information / 设备信息

OPPO A12, Android 9,arm64(I think)

### This issue has not been reported before / 这个问题还没有人反馈过

- [X] I have checked the Issues and found no similar issue reported / 我已经查看过 Issues，并且没有发现与之类似的问题被反馈

**Comment by Vera-Firefly** [comment]
Can you provide the complete log file?

**Comment by Mushrush825** [comment]
> Can you provide the complete log file?

You mean this?
[latestlog.txt](https://github.com/user-attachments/files/17598876/latestlog.txt)

**Comment by Mushrush825** [comment]
@Vera-Firefly are you fixing it?

**Comment by Mushrush825** [comment]
Thanks man it's fixed now thank you for your help <3
