### ISSUE TITLE
CRASH WITH CREATE ASTRAL MODPACK

### ISSUE THREAD

**Issue by GTG921** [MovTery/ZalithLauncher#216]
### Issue Type / 问题类型

Game Issue / 游戏问题

### Issue Description / 问题描述

WHEN I LOAD CREATE ASTRAL MODPACK THE GAME CTASHED.I TRIED CHANGING RENDER BUT NO USE.PLEASE GIVE ME SOLUTION

### Log File / 日志文件

[latestlog.txt](https://github.com/user-attachments/files/17641993/latestlog.txt)

### Android Version / Android 版本

14

### App Version / 应用版本

1.3.6

### Selected Renderer / 选择的渲染器

None

### Device Information / 设备信息

SAMSUNG F04,ANDROID 14,arm64

### This issue has not been reported before / 这个问题还没有人反馈过

- [X] I have checked the Issues and found no similar issue reported / 我已经查看过 Issues，并且没有发现与之类似的问题被反馈

**Comment by XZSAH** [comment]
java.lang.NullPointerException: get(...) must not be null
	at com.movtery.zalithlauncher.feature.download.platform.curseforge.CurseForgeCommonUtils$Companion.getDownloadSha1$ZalithLauncher_release(CurseForgeCommonUtils.kt:213)
	at com.movtery.zalithlauncher.feature.download.platform.curseforge.CurseForgeModPackInstallHelper$Companion.getModDownloader$lambda$3(CurseForgeModPackInstallHelper.kt:79)
	at com.movtery.zalithlauncher.feature.download.platform.curseforge.CurseForgeModPackInstallHelper$Companion.$r8$lambda$6lJboNIXzuYJ5smeslCpoR9w5wk(Unknown Source:0)
	at com.movtery.zalithlauncher.feature.download.platform.curseforge.CurseForgeModPackInstallHelper$Companion$$ExternalSyntheticLambda1.getFileInfo(D8$$SyntheticClass:0)
	at net.kdt.pojavlaunch.modloaders.modpacks.api.ModDownloader$FileInfoQueryTask.run(ModDownloader.java:98)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:644)
	at java.lang.Thread.run(Thread.java:1012)下载整合包应用大概率崩溃

**Comment by GTG921** [comment]
What can I  do please help me

**Comment by GTG921** [comment]
Being a indian I don't known Chinese please converse in english

**Comment by XZSAH** [comment]
In the latest version of the application, the application will crash when downloading the integration package. The above is the crash log. What can I do to make the application work properly

**Comment by GTG921** [comment]
You are telling to update the application

**Comment by MovTery** [comment]
I don't provide support for game crashes caused by running the modpack on mobile devices. This is due to the large number of mods, most of which are primarily intended for PC use. Compatibility issues on mobile are common, so please check which mods are causing the crashes.
