### ISSUE TITLE
bug Help

### ISSUE THREAD

**Issue by XZSAH** [MovTery/ZalithLauncher#217]
In the latest version of the application, the application will crash when downloading the integration package. The following is the application crash log.
   java.lang.NullPointerException: get(...) must not be null
at com.movtery.zalithlauncher.feature.download.platform.curseforge.CurseForgeCommonUtils$Companion.getDownloadSha1$ZalithLauncher_release(CurseForgeCommonUtils.kt:213)
at com.movtery.zalithlauncher.feature.download.platform.curseforge.CurseForgeModPackInstallHelper$Companion.getModDownloader$lambda$3(CurseForgeModPackInstallHelper.kt:79)
at com.movtery.zalithlauncher.feature.download.platform.curseforge.CurseForgeModPackInstallHelper$Companion.$r8$lambda$6lJboNIXzuYJ5smeslCpoR9w5wk(Unknown Source:0)
at com.movtery.zalithlauncher.feature.download.platform.curseforge.CurseForgeModPackInstallHelper$Companion$$ExternalSyntheticLambda1.getFileInfo(D8$$SyntheticClass:0)
at net.kdt.pojavlaunch.modloaders.modpacks.api.ModDownloader$FileInfoQueryTask.run(ModDownloader.java:98)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:644)
at java.lang.Thread.run(Thread.java:1012)

**Comment by MovTery** [comment]
更新你的启动器：

https://github.com/MovTery/ZalithLauncher/releases/tag/136400

**Comment by XZSAH** [comment]
> 更新你的启动器：
> 
> https://github.com/MovTery/ZalithLauncher/releases/tag/136400

在更新后与原版本没有区别，一样在下- 载整合包时应用会报错，详细信息:

java.net.ProtocolException: unexpected end of stream
	at com.android.okhttp.internal.http.Http1xStream$FixedLengthSource.read(Http1xStream.java:398)
	at com.android.okhttp.okio.RealBufferedSource$1.read(RealBufferedSource.java:372)
	at java.io.InputStream.read(InputStream.java:218)
	at net.kdt.pojavlaunch.utils.DownloadUtils.downloadFileMonitored(DownloadUtils.java:83)
	at net.kdt.pojavlaunch.modloaders.modpacks.api.ModDownloader$DownloadTask.tryDownload(ModDownloader.java:143)
	at net.kdt.pojavlaunch.modloaders.modpacks.api.ModDownloader$DownloadTask.lambda$run$0$net-kdt-pojavlaunch-modloaders-modpacks-api-ModDownloader$DownloadTask(ModDownloader.java:126)
	at net.kdt.pojavlaunch.modloaders.modpacks.api.ModDownloader$DownloadTask$$ExternalSyntheticLambda0.call(D8$$SyntheticClass:0)
	at net.kdt.pojavlaunch.utils.DownloadUtils.downloadFile(DownloadUtils.java:130)
	at net.kdt.pojavlaunch.utils.DownloadUtils.ensureSha1(DownloadUtils.java:155)
	at net.kdt.pojavlaunch.modloaders.modpacks.api.ModDownloader$DownloadTask.run(ModDownloader.java:125)
	at net.kdt.pojavlaunch.modloaders.modpacks.api.ModDownloader$FileInfoQueryTask.run(ModDownloader.java:101)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:644)
	at java.lang.Thread.run(Thread.java:1012)
