### ISSUE TITLE
The launcher keeps crashing every time i press start

### ISSUE THREAD

**Issue by Hsjshhhhjjsjwj** [MovTery/ZalithLauncher#262]
### Issue Type / 问题类型

Launcher Issue / 启动器问题

### Issue Description / 问题描述

Even if i try changing versions it still crashes i even changed the renderer but it still crashes!

### Log File / 日志文件

java.lang.RuntimeException: Unable to start activity ComponentInfo{com.movtery.zalithlauncher/net.kdt.pojavlaunch.MainActivity}: java.lang.RuntimeException: Activity does not exist.
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:4164)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:4322)
	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:103)
	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:139)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:96)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2685)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loopOnce(Looper.java:230)
	at android.os.Looper.loop(Looper.java:319)
	at android.app.ActivityThread.main(ActivityThread.java:8919)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:578)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1103)
Caused by: java.lang.RuntimeException: Activity does not exist.
	at com.movtery.zalithlauncher.context.ContextExecutor$Companion.getActivity(ContextExecutor.kt:133)
	at com.movtery.zalithlauncher.feature.customprofilepath.ProfilePathManager$Companion.getCurrentPath(ProfilePathManager.kt:30)
	at com.movtery.zalithlauncher.feature.customprofilepath.ProfilePathHome$Companion.getGameHome(ProfilePathHome.kt:7)
	at com.movtery.zalithlauncher.feature.version.Version.getGameDir(Version.kt:32)
	at net.kdt.pojavlaunch.MainActivity.onCreate(MainActivity.java:119)
	at android.app.Activity.performCreate(Activity.java:8975)
	at android.app.Activity.performCreate(Activity.java:8944)
	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1456)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:4146)
	... 12 more

### Android Version / Android 版本

14

### App Version / 应用版本

1.3.7.3

### Selected Renderer / 选择的渲染器

GL4ES

### Device Information / 设备信息

Samsung A15 ,android 14,arm64

### This issue has not been reported before / 这个问题还没有人反馈过

- [x] I have checked the Issues and found no similar issue reported / 我已经查看过 Issues，并且没有发现与之类似的问题被反馈

**Comment by MovTery** [comment]
I'm sorry for the poor experience I caused you. I have already fixed it and will release an urgent update shortly. I sincerely apologize.

**Comment by Hsjshhhhjjsjwj** [comment]
No problem man im happy to hear that you fixed it
