### ISSUE TITLE
Bug "Game path management" 

### ISSUE THREAD

**Issue by Lenttx** [MovTery/ZalithLauncher#264]
### Issue Type / 问题类型

Launcher Issue / 启动器问题

### Issue Description / 问题描述

I have changed the "Game Path Management" to "Storage/emulated/0/Minecraft Java Edition" and when trying to start the game in vanilla and also in fabric from that path I get an error, apparently what I saw and what I understood about the error that It seems to me that it is detecting the default path that ZalithLauncher comes with "Storage/emulated/0/Android/data/com.movtery.zalithlauncher/files" and not the path that I set "Storage/emulated/0/Minecraft Java Edition ", when I put a new path it still gives an error, but when I start the game from the default path of the ZalithLauncher "Storage/emulated/0/Android/data/com.movtery.zalithlauncher/files" it starts correctly, I hope it does fix as soon as possible

Another problem that I don't know if it happens only to me is that when I put an image in the "in-game interface" when I start the game it doesn't appear, once it appeared for a brief second but then it turned black 
The evidence of this other problem is in the comment
Thank you

Sorry if you don't understand, I speak Spanish and I use a translator to be able to translate everything into English.

### Log File / 日志文件

java.lang.RuntimeException: java.io.FileNotFoundException: /storage/emulated/0/Android/data/com.movtery.zalithlauncher/files/.minecraft/versions/Survival Fabric 1.20.1 /Survival Fabric 1.20.1 .json: open failed: ENOENT (No such file or directory)
	at net.kdt.pojavlaunch.Tools.getVersionInfo(Tools.java:556)
	at net.kdt.pojavlaunch.Tools.getVersionInfo(Tools.java:460)
	at net.kdt.pojavlaunch.MainActivity.initLayout(MainActivity.java:188)
	at net.kdt.pojavlaunch.MainActivity.onCreate(MainActivity.java:125)
	at android.app.Activity.performCreate(Activity.java:8214)
	at android.app.Activity.performCreate(Activity.java:8202)
	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1320)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:4033)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:4247)
	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:91)
	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:149)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:103)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2613)
	at android.os.Handler.dispatchMessage(Handler.java:110)
	at android.os.Looper.loop(Looper.java:219)
	at android.app.ActivityThread.main(ActivityThread.java:8668)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:513)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1109)
Caused by: java.io.FileNotFoundException: /storage/emulated/0/Android/data/com.movtery.zalithlauncher/files/.minecraft/versions/Survival Fabric 1.20.1 /Survival Fabric 1.20.1 .json: open failed: ENOENT (No such file or directory)
	at libcore.io.IoBridge.open(IoBridge.java:496)
	at java.io.FileInputStream.<init>(FileInputStream.java:159)
	at java.io.FileInputStream.<init>(FileInputStream.java:115)
	at net.kdt.pojavlaunch.Tools.read(Tools.java:584)
	at net.kdt.pojavlaunch.Tools.getVersionInfo(Tools.java:466)
	... 18 more
Caused by: android.system.ErrnoException: open failed: ENOENT (No such file or directory)
	at libcore.io.Linux.open(Native Method)
	at libcore.io.ForwardingOs.open(ForwardingOs.java:167)
	at libcore.io.BlockGuardOs.open(BlockGuardOs.java:252)
	at libcore.io.ForwardingOs.open(ForwardingOs.java:167)
	at android.app.ActivityThread$AndroidOs.open(ActivityThread.java:8464)
	at libcore.io.IoBridge.open(IoBridge.java:482)
	... 22 more

### Screenshots or Videos / 截图或视频

![Screenshot_20241119_194914_com movtery zalithlauncher](https://github.com/user-attachments/assets/7f9964b9-edc9-4532-9b2b-c06fc17077b8)

https://github.com/user-attachments/assets/ac0e593f-692d-4a00-a5ec-b4e9928b5a0d

### Reproduction Steps / 复现步骤

```markdown
1. Enter ZalithLauncher
2. Enter version management
3. Choose a route different from the default
4. Start game
```

### Android Version / Android 版本

10

### App Version / 应用版本

1.3.7.3

### Selected Renderer / 选择的渲染器

None

### Device Information / 设备信息

Huawei P40 lite, android 10

### This issue has not been reported before / 这个问题还没有人反馈过

- [X] I have checked the Issues and found no similar issue reported / 我已经查看过 Issues，并且没有发现与之类似的问题被反馈

**Comment by Lenttx** [comment]
https://github.com/user-attachments/assets/7c7a17bc-3360-461b-bd6f-a26c998a05d5

![Screenshot_20241119_201727_com movtery zalithlauncher](https://github.com/user-attachments/assets/19eb1569-bcd9-442d-8275-eb74bf58e68f)
![Screenshot_20241119_201803_com movtery zalithlauncher](https://github.com/user-attachments/assets/c86f1f6c-525e-4a6f-9970-b8e5769739f9)

**Comment by MovTery** [comment]
Thank you for your feedback. I have already fixed it, and the change will take effect in the next version of the launcher. Sorry for any inconvenience caused.
