### ISSUE TITLE
i get error while downloading modpack

### ISSUE THREAD

**Issue by maulnaamalik** [MovTery/ZalithLauncher#276]
i tried to download the modpack (Skyfactory4) with new version of launcher and got a message like this,

```
java.io.IOException: Unable to download from https://maven.minecraftforge.net/net/minecraftforge/forge/maven-metadata.xml
	at net.kdt.pojavlaunch.utils.DownloadUtils.download(DownloadUtils.java:44)
	at net.kdt.pojavlaunch.utils.DownloadUtils.download(DownloadUtils.java:28)
	at net.kdt.pojavlaunch.utils.DownloadUtils.downloadString(DownloadUtils.java:58)
	at net.kdt.pojavlaunch.utils.DownloadUtils.downloadStringCached(DownloadUtils.java:107)
	at net.kdt.pojavlaunch.modloaders.ForgeUtils.downloadForgeVersions(ForgeUtils.java:23)
	at com.movtery.zalithlauncher.feature.mod.modloader.ForgeDownloadTask.findVersion(ForgeDownloadTask.java:69)
	at com.movtery.zalithlauncher.feature.mod.modloader.ForgeDownloadTask.determineDownloadUrl(ForgeDownloadTask.java:62)
	at com.movtery.zalithlauncher.feature.mod.modloader.ForgeDownloadTask.run(ForgeDownloadTask.java:38)
	at com.movtery.zalithlauncher.feature.download.platform.AbstractPlatformHelper.install$lambda$9$lambda$4(AbstractPlatformHelper.kt:92)
	at com.movtery.zalithlauncher.feature.download.platform.AbstractPlatformHelper.$r8$lambda$5n2rXKh7xV80yBdnmSJQ46N7oSo(Unknown Source:0)
	at com.movtery.zalithlauncher.feature.download.platform.AbstractPlatformHelper$$ExternalSyntheticLambda6.call(D8$$SyntheticClass:0)
	at com.movtery.zalithlauncher.task.SimpleTask.performMainTask(SimpleTask.kt:7)
	at com.movtery.zalithlauncher.task.Task.execute$lambda$7(Task.kt:108)
	at com.movtery.zalithlauncher.task.Task.$r8$lambda$a6le3neP0xqzz8XnLILJ3oRQma8(Unknown Source:0)
	at com.movtery.zalithlauncher.task.Task$$ExternalSyntheticLambda1.run(D8$$SyntheticClass:0)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
	at java.lang.Thread.run(Thread.java:764)
Caused by: java.net.SocketTimeoutException: timeout
	at com.android.okhttp.okio.Okio$3.newTimeoutException(Okio.java:212)
	at com.android.okhttp.okio.AsyncTimeout.exit(AsyncTimeout.java:261)
	at com.android.okhttp.okio.AsyncTimeout$2.read(AsyncTimeout.java:215)
	at com.android.okhttp.okio.RealBufferedSource.indexOf(RealBufferedSource.java:306)
	at com.android.okhttp.okio.RealBufferedSource.indexOf(RealBufferedSource.java:300)
	at com.android.okhttp.okio.RealBufferedSource.readUtf8LineStrict(RealBufferedSource.java:196)
	at com.android.okhttp.internal.http.Http1xStream.readResponse(Http1xStream.java:186)
	at com.android.okhttp.internal.http.Http1xStream.readResponseHeaders(Http1xStream.java:127)
	at com.android.okhttp.internal.http.HttpEngine.readNetworkResponse(HttpEngine.java:763)
	at com.android.okhttp.internal.http.HttpEngine.readResponse(HttpEngine.java:635)
	at com.android.okhttp.internal.huc.HttpURLConnectionImpl.execute(HttpURLConnectionImpl.java:471)
	at com.android.okhttp.internal.huc.HttpURLConnectionImpl.getResponse(HttpURLConnectionImpl.java:407)
	at com.android.okhttp.internal.huc.HttpURLConnectionImpl.getResponseCode(HttpURLConnectionImpl.java:538)
	at com.android.okhttp.internal.huc.DelegatingHttpsURLConnection.getResponseCode(DelegatingHttpsURLConnection.java:105)
	at com.android.okhttp.internal.huc.HttpsURLConnectionImpl.getResponseCode(Unknown Source:0)
	at net.kdt.pojavlaunch.utils.DownloadUtils.download(DownloadUtils.java:37)
	... 17 more
Caused by: java.net.SocketException: socket is closed
	at com.android.org.conscrypt.ConscryptFileDescriptorSocket$SSLInputStream.read(ConscryptFileDescriptorSocket.java:546)
	at com.android.okhttp.okio.Okio$2.read(Okio.java:136)
	at com.android.okhttp.okio.AsyncTimeout$2.read(AsyncTimeout.java:211)
	... 30 more
```

the good news is all the mods are downloaded, but there are some important modpack files missing, which makes the modpack unable to run. if i run the modpack, there is a message in screen
![Screenshot_2024-11-24-20-23-33-42](https://github.com/user-attachments/assets/b9b7b55c-39ae-4680-9644-00a675765d8b)

```
The current version is missing the version JSON file and is therefore
considered an invalid version bla bla bla
```
and the launcher tells me to delete the modpack files
-_-

aghhh I'm tired, this is wasting my time

so what do you think?

NOTE: my launcher version is 1.3.7.5

**Comment by maulnaamalik** [comment]
Thank for fix this bug:D
